### ISSUE TITLE
specify urllib3 version requirement in setup.py

### ISSUE THREAD

**Issue by dpinol** [pusher/pusher-http-python#142]
Hi,
I've seen that requirement.txt has "urllib3==1.24" (as many other libraries, eg. requests) which forbid version 1.25). But setup.py does not contain any version specification for urllib3. 
Can you add the requirement also in setup.py? Otherwise setup.py causes 1.25 to be installed, which conflicts with other libraries which forbid it

thanks

**Comment by WillSewell** [comment]
Thanks for reporting this. It looks like `requests` dropped support for `urllib3==1.25` due to a security vulnerability https://github.com/kennethreitz/requests/issues/5065.

I don't want to pin to a specific version of `urllib3` in `setup.py` because users of this library should have as much flexibility as possible in terms of the versions of other dependencies they can use. However I'm happy to take the same approach as `requests` and drop support just for vulnerable versions of `urllib3`.

**Comment by WillSewell** [comment]
Thanks for letting us know about this.

I'd like to avoid pinning to a specific version of urllib3 in setup.py because ideally users of this library should have as much flexibility as possible in terms of the versions of other dependencies they can use. It's the responsibility of the user of the library and their package manager to install compatible versions.

The latest version of `urllib3` ([1.5.2](https://github.com/urllib3/urllib3/releases/tag/1.25.2)) _is_ compatible with the latest version of `requests` ([2.22.0](https://github.com/kennethreitz/requests/releases/tag/v2.22.0)), so installing the latest versions of both should lead to now issues. Please let me know if I'm missing something.
