### ISSUE TITLE
Timeout type forced to be integer

### ISSUE THREAD

**Issue by ysaunier** [pusher/pusher-http-python#194]
Hi team! 👋

Just a quick question: Why did you set a validation that the timeout type must be an integer? (cf. [your validation](https://github.com/pusher/pusher-http-python/blob/master/pusher/client.py#L63-L64)).
According to the `requests` documentation, the accepted type is a `float`. (cf. [the documentation](https://github.com/psf/requests/blob/main/requests/api.py#L32-L34)). 

This is painful because we are forced to set seconds with your timeout when we would like to define milliseconds.

**Comment by edmundlam** [comment]
I wonder if we could also allow a tuple of numbers as well, since `requests` also allows it. 

For example, a `timeout=(5, 27)` will set a connection timeout of 5 seconds, and a read timeout of 27 seconds. If you are open to this change, I'd be happy to adjust my PR to account for tuples. 

Ref: https://requests.readthedocs.io/en/latest/user/advanced/#timeouts

**Comment by benjamin-tang-pusher** [comment]
Thanks @edmundlam, I will give it a test and approve it.

**Comment by benjamin-tang-pusher** [comment]
#195 released in 3.3.1
